openapi: "3.0.0"
info:
  version: 1.0.0
  title: Car Reservation Service API
paths:

  ##################################################################################################
  # Car
  ##################################################################################################

  "/car":
    $ref: "car/api.yml#/car"

  "/car/{carId}":
    $ref: "car/api.yml#/carById"


  ##################################################################################################
  # Car Reservation
  ##################################################################################################

  "/reservation/car":
    $ref: "reservation/api.yml#/reservation"